/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GalleryGrid: typeof import('./src/components/GalleryGrid.vue')['default']
    GalleryModal: typeof import('./src/components/GalleryModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageCard: typeof import('./src/components/ImageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewToggle: typeof import('./src/components/ViewToggle.vue')['default']
  }
}
